import type { SiteContent } from './content'

export const defaultContent: SiteContent = {
  meta: {
    title: 'e-techbike.at — Elektromobilität Graz',
    description: 'Premium E-Bikes, E-Scooter und E-Motorräder. Direktimporteur in Graz. 2 Jahre Garantie.',
    primaryColor: '#0099CC',
    accentColor: '#B3E600',
    font: "system-ui, -apple-system, 'Segoe UI', sans-serif",
  },
  nav: {
    logo: 'uploads/etb-logo.jpg',
    brand: 'e-techbike.at',
    links: [
      { label: 'Sortiment', href: '#products' },
      { label: 'Förderungen', href: '#foerderung' },
      { label: 'Standort', href: '#location' },
      { label: 'Neuigkeiten', href: '#news' },
    ],
    phone: '+43 664 7372 6965',
    ctaLabel: 'Beratung anfragen',
    ctaHref: '#location',
  },
  hero: {
    tag: 'Direktimporteur · Graz · Österreich',
    headline: 'Elektro&shy;mobilität.<br><span>Jetzt.</span>',
    subheadline: 'Premium E-Bikes, E-Scooter und E-Motorräder — direkt vom Hersteller, mit voller Garantie und persönlicher Beratung in Graz.',
    ctaLabel: 'Sortiment entdecken',
    ctaHref: '#products',
    ctaSecLabel: 'Beratung anfragen',
    ctaSecHref: '#location',
    image: 'uploads/etb-rks-mx25.jpg',
    bgX: 50,
    bgY: 40,
    minHeight: 680,
  },
  trust: {
    items: [
      { id: 't1', icon: 'delivery', bold: '5–7 Tage', text: 'Versand österreichweit' },
      { id: 't2', icon: 'shield', bold: '2 Jahre', text: 'Herstellergarantie' },
      { id: 't3', icon: 'tag', bold: 'Direktimport', text: 'kein Aufschlag' },
      { id: 't4', icon: 'location', bold: 'Beratung', text: 'in Graz' },
    ],
  },
  categories: {
    eyebrow: 'Sortiment',
    title: 'Für jeden das richtige Fahrzeug',
    items: [
      {
        id: 'cat-scooter25',
        name: 'E-Scooter 25 km/h',
        sub: 'Führerscheinfrei ab 16',
        image: 'uploads/etb-moped-city-silver.jpg',
      },
      {
        id: 'cat-scooter45',
        name: 'E-Scooter 45 km/h',
        sub: 'Führerschein AM · L3e',
        image: 'uploads/etb-tailg-runner-hd.png',
      },
      {
        id: 'cat-emot',
        name: 'E-Motorrad',
        sub: '100 km/h · 6000W',
        image: 'uploads/etb-moped-white-45.png',
      },
      {
        id: 'cat-bike-falt',
        name: 'Elektrofahrrad Klappbar',
        sub: 'Kompakt & alltagstauglich',
        image: 'uploads/etb-rks-faltbike.jpg',
      },
      {
        id: 'cat-bike-city',
        name: 'City E-Bikes',
        sub: 'Komfort für Stadt & Tour',
        image: 'uploads/etb-rks-mx25-life.jpg',
      },
      {
        id: 'cat-bike-mtn',
        name: 'Mountain E-Bikes',
        sub: 'Fat Tire · Gelände · Power',
        image: 'uploads/etb-ape-ryder-tan.jpg',
      },
      {
        id: 'cat-kab',
        name: 'Kabinenroller',
        sub: 'Überdacht · wetterfest',
        image: 'uploads/etb-kabinenmobil-x3.png',
      },
      {
        id: 'cat-senior',
        name: 'E-Seniorenmobil',
        sub: 'Stabil & komfortabel',
        image: 'uploads/etb-dreirad-3q.png',
      },
      {
        id: 'cat-transport',
        name: 'E-Transporter',
        sub: 'Cargo · Lieferung · Nutzfahrzeug',
        image: 'uploads/etb-eauto-side.jpg',
      },
      {
        id: 'cat-bat',
        name: 'Akkus',
        sub: 'Bleigel · Lithium',
        image: 'uploads/etb-akku-li-48v.jpg',
        subcategories: [
          { id: 'sub-bat-agm', name: 'Bleigel / AGM', image: 'uploads/etb-akku-48v.jpg', description: 'Robust und wartungsarm' },
          { id: 'sub-bat-li', name: 'Lithium', image: 'uploads/etb-akku-li-48v.jpg', description: 'Leicht, leistungsstark, langlebig' },
        ],
      },
    ],
  },
  products: {
    title: 'Bestseller',
    tabs: ['Alle', 'E-Bikes', 'E-Mopeds', 'E-Scooter', 'Senioren', 'Batterien'],
    items: [
      {
        id: 'p1',
        name: 'Skyjet RV10 Plus Shimano',
        badge: '',
        category: 'Elektrofahrrad Klappbar',
        description: 'Falt-E-Bike mit 20" × 4.0" Fat Tires, HUPO 36V 15Ah Akku und bis 80 km Reichweite. Gepäckträger inklusive.',
        price: '€1.190,00',
        image: 'uploads/etb-rks-faltbike.jpg',
        specs: ['250–600W', '36V 15Ah', 'bis 80 km', '4.0" Fat Tire'],
        specsTable: [
          { label: 'Motor', value: '250–600W' },
          { label: 'Akku', value: 'HUPO 36V / 15Ah' },
          { label: 'Reichweite', value: 'bis 80 km' },
          { label: 'Ladezeit', value: '4–6 Stunden' },
          { label: 'Höchstgeschwindigkeit', value: '25 km/h' },
          { label: 'Rahmen', value: '20 Zoll Aluminium, faltbar' },
          { label: 'Reifen', value: '20 × 4.0' },
          { label: 'Schaltung', value: 'Shimano 7-Gang' },
          { label: 'Bremsen', value: 'Scheibenbremsen vorne & hinten' },
          { label: 'Display', value: 'LCD integriert' },
          { label: 'Federgabel', value: 'einstellbar' },
          { label: 'Ausstattung', value: 'Gepäckträger, Licht, Reflektoren, Hupe' },
        ],
        details: '<ul><li>Faltbar für einfachen Transport und Lagerung</li><li>Batterie mit Sicherheitsschloss</li><li>Gepäckträger serienmäßig</li><li>CE-zertifiziert, führerscheinfrei ab 14 Jahren</li><li>Förderfähig: €500 E-Klapprad Förderung</li></ul>',
        delivery: 'Kostenloser Versand österreichweit. Lieferzeit 5–7 Werktage.',
      },
      {
        id: 'p2',
        name: 'MX25 PRO Shimano',
        badge: 'Aktion',
        category: 'Elektrofahrrad Klappbar',
        description: 'Kompaktes Falt-E-Bike im Angebot. 20" Räder, Shimano 6-Gang, Akku wählbar bis 240 km Reichweite.',
        price: '€650,00',
        image: 'uploads/etb-rks-mx25.jpg',
        images: ['uploads/etb-rks-mx25.jpg', 'uploads/etb-rks-mx25-life.jpg'],
        specs: ['250–600W', '36V wählbar', 'bis 240 km', 'Shimano 6G'],
        specsTable: [
          { label: 'Motor', value: '250–600W' },
          { label: 'Akku', value: '36V 7,8 Ah / 10 Ah / 35 Ah (wählbar)' },
          { label: 'Reichweite', value: '30–240 km (je nach Akku)' },
          { label: 'Ladezeit', value: '4–6 Stunden' },
          { label: 'Rahmen', value: '20 Zoll, Stahlrahmen faltbar' },
          { label: 'Reifen', value: '20 × 1.95 Zoll' },
          { label: 'Schaltung', value: 'Shimano 6-Gang' },
          { label: 'Bremsen', value: 'Scheibenbremse' },
          { label: 'Display', value: 'LCD' },
          { label: 'Ausstattung', value: 'Gepäckträger, Licht, Reflektoren, Hupe' },
        ],
        details: '<ul><li>Einlegebatterie mit Sicherheitsverriegelung</li><li>Akku-Variante frei wählbar — von Kurzstrecke bis 240 km</li><li>Aluminium Kotflügel</li><li>CE-zertifiziert, führerscheinfrei ab 14 Jahren</li><li>Förderfähig: €500 E-Klapprad Förderung</li></ul>',
        delivery: 'Kostenloser Versand österreichweit. Lieferzeit 5–7 Werktage.',
      },
      {
        id: 'p26',
        name: 'Skyjet Nitro-16',
        badge: '',
        category: 'Elektrofahrrad Klappbar',
        description: 'Kompaktes 16" Falt-E-Bike — das kleinste und leichteste im Sortiment. Ideal für U-Bahn und Büro.',
        price: '€590,00',
        image: 'uploads/etb-rks-mx25.jpg',
        specs: ['250–600W', '36V 7,8Ah', 'bis 30 km', '16 Zoll'],
        specsTable: [
          { label: 'Motor', value: '250–600W' },
          { label: 'Akku', value: '36V / 7,8Ah' },
          { label: 'Reichweite', value: 'bis 30 km' },
          { label: 'Ladezeit', value: '4–6 Stunden' },
          { label: 'Rahmen', value: '16 Zoll, Stahlrahmen faltbar' },
          { label: 'Reifen', value: 'KENDA 16" × 1.95' },
          { label: 'Max. Zuladung', value: '114 kg' },
          { label: 'Schaltung', value: 'Shimano 6-Gang' },
          { label: 'Bremsen', value: 'Scheibenbremse' },
          { label: 'Display', value: 'LCD' },
          { label: 'Ausstattung', value: 'Gepäckträger, Licht, Reflektoren, Hupe' },
        ],
        details: '<ul><li>Kleinstes Faltrad im Sortiment — ideal für Pendler</li><li>Einlegebatterie mit Sicherheitsverriegelung</li><li>KENDA Qualitätsbereifung</li><li>CE-zertifiziert, führerscheinfrei ab 14 Jahren</li><li>Förderfähig: €500 E-Klapprad Förderung</li></ul>',
        delivery: 'Kostenloser Versand österreichweit. Lieferzeit 5–7 Werktage.',
      },
      {
        id: 'p27',
        name: 'RSIII PRO Shimano',
        badge: '',
        category: 'Elektrofahrrad Klappbar',
        description: 'Falt-E-Bike mit 20" × 4.0" Fat Tires und HUPO Akku bis 240 km Reichweite. Shimano MF-TZ500, USB-Port.',
        price: '€1.040,00',
        image: 'uploads/etb-rks-fat-grey.png',
        specs: ['250W', '36V 10/35Ah', 'bis 240 km', '4.0" Fat Tire'],
        specsTable: [
          { label: 'Motor', value: '250W' },
          { label: 'Akku', value: 'HUPO 36V 10 Ah / 35 Ah (wählbar)' },
          { label: 'Reichweite', value: 'bis 240 km (mit 35Ah)' },
          { label: 'Ladezeit', value: '4–6 Stunden' },
          { label: 'Höchstgeschwindigkeit', value: '25 km/h' },
          { label: 'Rahmen', value: '20 Zoll Aluminium, faltbar' },
          { label: 'Reifen', value: '20 × 4.0' },
          { label: 'Schaltung', value: 'Shimano MF-TZ500 7-Gang' },
          { label: 'Bremsen', value: 'Scheibenbremsen vorne & hinten' },
          { label: 'Display', value: 'LCD integriert' },
          { label: 'Federgabel', value: 'einstellbar' },
          { label: 'Ausstattung', value: 'Gepäckträger, Licht, Reflektoren, Hupe, USB' },
        ],
        details: '<ul><li>Maximale Reichweite bis 240 km mit 35Ah Akku</li><li>Fat Tire 20" × 4.0" für Stadt und Gelände</li><li>USB-Port am Akku zum Laden von Geräten</li><li>Batterie mit Sicherheitsschloss</li><li>CE-zertifiziert, führerscheinfrei</li><li>Förderfähig: €500 E-Klapprad Förderung</li></ul>',
        delivery: 'Kostenloser Versand österreichweit. Lieferzeit 5–7 Werktage.',
      },
      {
        id: 'p28',
        name: 'RSI-X PRO Shimano',
        badge: '',
        category: 'Elektrofahrrad Klappbar',
        description: 'Falt-E-Bike mit 20" × 4.0" Fat Tires und HUPO Akku bis 240 km. Shimano MF-TZ500, USB-Port.',
        price: '€1.040,00',
        image: 'uploads/etb-rks-fat-black.jpg',
        specs: ['250W', '36V 10/35Ah', 'bis 240 km', '4.0" Fat Tire'],
        specsTable: [
          { label: 'Motor', value: '250W' },
          { label: 'Akku', value: 'HUPO 36V 10 Ah / 35 Ah (wählbar)' },
          { label: 'Reichweite', value: 'bis 240 km (mit 35Ah)' },
          { label: 'Ladezeit', value: '4–6 Stunden' },
          { label: 'Höchstgeschwindigkeit', value: '25 km/h' },
          { label: 'Rahmen', value: '20 Zoll Aluminium, faltbar' },
          { label: 'Reifen', value: '20 × 4.0' },
          { label: 'Schaltung', value: 'Shimano MF-TZ500 7-Gang' },
          { label: 'Bremsen', value: 'Scheibenbremsen vorne & hinten' },
          { label: 'Display', value: 'LCD integriert' },
          { label: 'Federgabel', value: 'einstellbar' },
          { label: 'Ausstattung', value: 'Gepäckträger, Licht, Reflektoren, Hupe, USB' },
        ],
        details: '<ul><li>Sportlichere Variante des RSIII PRO</li><li>Fat Tire 20" × 4.0" für Stadt und Gelände</li><li>USB-Port am Akku</li><li>Batterie mit Sicherheitsschloss</li><li>CE-zertifiziert, führerscheinfrei</li><li>Förderfähig: €500 E-Klapprad Förderung</li></ul>',
        delivery: 'Kostenloser Versand österreichweit. Lieferzeit 5–7 Werktage.',
      },
      {
        id: 'p3',
        name: 'TailG E-Moped Runner',
        badge: 'Beliebt',
        category: 'E-Scooter 45 km/h',
        description: 'Straßenzugelassenes E-Moped mit Topcase inklusive. 45 km/h, volle StVO-Zulassung.',
        price: '€2.050,00',
        image: 'uploads/etb-tailg-runner-hd.png',
        specs: ['45 km/h', '60 km', 'Topcase', 'StVO'],
        specsTable: [
          { label: 'Nennleistung', value: '2000W' },
          { label: 'Höchstgeschwindigkeit', value: '45 km/h' },
          { label: 'Akku', value: '72V 25Ah Lithium (opt. 2 Batterien +€540)' },
          { label: 'Reichweite', value: '60 km (100 km mit 2 Batterien)' },
          { label: 'Ladezeit', value: '3–6 Stunden' },
          { label: 'Bremsen', value: 'F: Scheibenbremse · R: Trommelbremse' },
          { label: 'Reifen', value: 'F: 90/70-12 · R: 90/70-12' },
          { label: 'Zulassung', value: 'CE/EEC · L3e · StVO-konform' },
          { label: 'Führerschein', value: 'Klasse A1 oder AM' },
          { label: 'Gesamtmaße', value: '1850 × 735 × 1110 mm' },
          { label: 'Gewicht', value: '71 kg (ohne Batterie)' },
          { label: 'Radstand', value: '1330 mm' },
          { label: 'Sitzhöhe', value: '730 mm' },
        ],
        details: '<ul><li>Kraftvoller 2000W Motor, beschleunigt auf 45 km/h</li><li>Reichweite bis 100 km mit optionaler 2. Batterie</li><li>Hydraulische Federung, ergonomisches Sitzpolster</li><li>Verlängerter Radstand für Stabilität und agiles Handling</li><li>CE/EEC zertifiziert, vollständige Straßenzulassung</li><li>Vormontierte Lieferung (ca. 90%)</li><li>Förderfähig: bis zu €600 E-Mobilitätsbonus (eRide 2025)</li></ul>',
        delivery: 'Lieferung frei Haus österreichweit, 5–7 Werktage. Montage und Einweisung in Graz möglich.',
      },
      {
        id: 'p4',
        name: 'Bikely ZL9 E-Moped',
        badge: '',
        category: 'E-Scooter 25 km/h',
        description: 'Kompaktes E-Moped 25 km/h mit auswechselbarem Akku. Transportbox inklusive, ideal für die Stadt.',
        price: '€890,00',
        image: 'uploads/etb-bikely-zl9.jpg',
        specs: ['25 km/h', 'bis 180 km', 'Transportbox', 'führerscheinfrei'],
        specsTable: [
          { label: 'Motor', value: '600W / 48V' },
          { label: 'Höchstgeschwindigkeit', value: '25 km/h' },
          { label: 'Reichweite', value: '20Ah: bis 50 km · 25Ah: bis 60 km · 78Ah: bis 180 km' },
          { label: 'Batterietyp', value: 'Li-Ion, tragbar & austauschbar' },
          { label: 'Ladezeit', value: '6–8 Stunden' },
          { label: 'Ladegerät', value: '48V 5A / 8A / 15A' },
          { label: 'Reifen', value: '3.00 × 10 Tubeless' },
          { label: 'Bremsen', value: 'Scheibenbremse' },
          { label: 'Max. Zuladung', value: '150 kg' },
          { label: 'Steigung', value: '15%' },
          { label: 'Ausstattung', value: '2 Spiegel, Transportbox, Hupe, Alarm' },
          { label: 'Maße', value: '1680 × 710 × 1050 mm' },
          { label: 'Gewicht', value: '55 kg (ohne Akku)' },
        ],
        details: '<ul><li>Auswechselbarer Akku — aufladen am Fahrzeug oder zu Hause</li><li>Transportbox hinten serienmäßig</li><li>Alarmanlage inklusive</li><li>USB-Ladeanschluss</li><li>CE/EEC zertifiziert, auf Radweg zugelassen</li><li>Vormontierte Lieferung (ca. 90%)</li></ul>',
        delivery: 'Kostenloser Versand österreichweit. Lieferzeit 5–7 Werktage.',
      },
      {
        id: 'p5',
        name: 'Lithium Akku 48V 25Ah',
        badge: '',
        category: 'Akkus',
        subcategory: 'sub-bat-li',
        description: 'Hochleistungs-Lithium-Akku mit BMS-Schutz, 3.000+ Ladezyklen, 5 Jahre Garantie.',
        price: 'ab €599',
        image: 'uploads/etb-akku-48v.jpg',
        specs: ['48V', '25Ah', 'BMS', '3.000+ Zyklen'],
        specsTable: [
          { label: 'Technologie', value: 'Lithium-Ionen' },
          { label: 'Spannung', value: '48V' },
          { label: 'Kapazität', value: '25Ah' },
          { label: 'Anschluss', value: 'XT60 / Anderson' },
          { label: 'Ladezyklen', value: '3.000+' },
          { label: 'BMS-Schutz', value: 'Überspannung, Tiefentladung, Temperatur' },
          { label: 'Gewicht', value: '~5,5 kg' },
          { label: 'Ladezeit', value: 'ca. 5–7 Stunden' },
        ],
        details: '<ul><li>Anwendungsbereiche: E-Bikes, E-Scooter, Elektromobile, Segel- und Elektroboote, Wohnwagen, Windenergieanlagen, Solaranlagen, Weidezäune, Reha-Technik</li><li>Integriertes BMS (Battery Management System)</li><li>Temperaturschutz und Überladeschutz</li><li>5 Jahre Herstellergarantie</li></ul>',
        delivery: 'Kostenloser Versand österreichweit. Lieferzeit 3–5 Werktage.',
      },
      {
        id: 'p6',
        name: 'KUBA Grape 25 MAX',
        badge: '',
        category: 'Kabinenroller',
        description: 'Überdachtes 3-rädriges Seniorenmobil mit CE/EEC-Zulassung, 25 km/h.',
        price: 'ab €1.890',
        image: 'uploads/etb-kuba-grape-v2.png',
        specs: ['25 km/h', '3-rädrig', 'Überdachung', 'CE/EEC'],
        specsTable: [
          { label: 'Höchstgeschwindigkeit', value: '25 km/h' },
          { label: 'Antrieb', value: '3-rädrig, elektrisch' },
          { label: 'Motor', value: '1200W BLDC' },
          { label: 'Akku', value: '60V / 20Ah Lithium' },
          { label: 'Reichweite', value: 'bis 60 km' },
          { label: 'Überdachung', value: 'Ja, wetterfest' },
          { label: 'Zulassung', value: 'CE/EEC, L2e' },
          { label: 'Max. Zuladung', value: '200 kg' },
        ],
        details: '<ul><li>Vollständige Witterungsschutz-Kabine</li><li>Heizung optional erhältlich</li><li>Elektrische Servolenkung</li><li>Rückfahrkamera serienmäßig</li><li>Zugelassen für öffentlichen Straßenverkehr</li></ul>',
        delivery: 'Lieferung frei Haus, 7–14 Werktage. Persönliche Einweisung und Probefahrt in Graz.',
      },
      {
        id: 'p7',
        name: 'Bleigel Akku 12V 20Ah',
        badge: '',
        category: 'Akkus',
        subcategory: 'sub-bat-agm',
        description: 'VRLA Bleigel Deep-Cycle Batterie. Wartungsfrei, robust, vielseitig einsetzbar.',
        price: '€55,00',
        regularPrice: '€75,00',
        image: 'uploads/etb-akku-48v.jpg',
        specs: ['12V', '20Ah', 'AGM', 'Deep Cycle'],
        specsTable: [
          { label: 'Technologie', value: 'AGM / Bleigel' },
          { label: 'Spannung', value: '12V' },
          { label: 'Kapazität', value: '20Ah' },
          { label: 'Anschluss', value: 'F11 (M6)' },
          { label: 'Typ', value: 'Deep Cycle, VRLA' },
          { label: 'Wartung', value: 'wartungsfrei' },
          { label: 'Maße (B×H×T)', value: '181 × 167 × 77 mm' },
          { label: 'Gewicht', value: 'ca. 5,8 kg' },
        ],
        details: '<ul><li>Anwendungsbereiche: Reha-Technik (Rollstühle, Lifter, Seniorenmobile), E-Scooter, Elektromobile, Segel- und Elektroboote, Wohnwagen, Windenergieanlagen, Solaranlagen, Weidezäune</li><li>VRLA-versiegelt, auslaufsicher</li><li>Wartungsfreier Betrieb</li><li>UL- und CE-zertifiziert</li></ul>',
        delivery: 'Kostenloser Versand österreichweit. Lieferzeit 2–4 Werktage.',
      },
      {
        id: 'p8',
        name: 'Bikely E-Moped 45 km/h',
        badge: 'Neu',
        category: 'E-Scooter 45 km/h',
        description: 'Straßenzugelassenes E-Moped 45 km/h mit Topcase. Bikely-Design, LED rundum.',
        price: 'auf Anfrage',
        image: 'uploads/etb-bikely-moped-45.jpg',
        specs: ['45 km/h', 'Topcase', 'LED', 'StVO'],
        specsTable: [
          { label: 'Motor', value: '60V 3000W' },
          { label: 'Höchstgeschwindigkeit', value: '45 km/h' },
          { label: 'Reichweite', value: 'bis 120 km' },
          { label: 'Akkukapazität', value: '72V 20Ah' },
          { label: 'Batterietyp', value: 'Li-Ion / Bleigel' },
          { label: 'Ladezeit', value: '6–7 Stunden' },
          { label: 'Ladegerät', value: '60V / 3A' },
          { label: 'Reifen', value: 'Vorderrad 17 Zoll · Hinterrad 13 Zoll Tubeless' },
          { label: 'Bremsen', value: 'Scheibenbremsen / Trommelbremsen' },
          { label: 'Max. Zuladung', value: '149 kg' },
          { label: 'Steigung', value: '20%' },
          { label: 'Gewicht', value: '96 kg' },
          { label: 'Ausstattung', value: '2 Rückspiegel' },
          { label: 'Zulassung', value: 'CE/EEC · L3e · StVO-konform' },
          { label: 'Führerschein', value: 'Klasse A1 oder AM' },
        ],
        details: '<ul><li>3000W Motor für kraftvollen Chopper-Antrieb</li><li>Harley-Davidson Chopper-Silhouette im Elektromotorrad</li><li>Bis 120 km Reichweite</li><li>Erhältlich in Schwarz und Rot</li><li>CE/EEC zertifiziert, vollständige Straßenzulassung</li><li>Förderfähig: bis zu €600 E-Mobilitätsbonus (eRide 2025)</li></ul>',
        delivery: 'Lieferung frei Haus österreichweit. Persönliche Einweisung in Graz möglich.',
      },
      {
        id: 'p9',
        name: 'RKS Fat Fold E-Bike',
        badge: '',
        category: 'Mountain E-Bikes',
        description: 'Faltbares Fat Bike mit 20" Ballonreifen. Perfekt für Gelände und Stadt.',
        price: 'auf Anfrage',
        image: 'uploads/etb-rks-fat-grey.png',
        specs: ['Fat Tire', 'faltbar', '250W', '25 km/h'],
        specsTable: [
          { label: 'Reifengröße', value: '20" × 4.0 Fat Tire' },
          { label: 'Motor', value: '250W Heckmotor' },
          { label: 'Höchstgeschwindigkeit', value: '25 km/h' },
          { label: 'Rahmen', value: 'Aluminium, faltbar' },
          { label: 'Bremsen', value: 'Hydraulische Scheibenbremsen' },
          { label: 'Schaltung', value: 'Shimano 7-Gang' },
        ],
        details: '<ul><li>Geländetauglich durch breite 4.0" Fat Tires</li><li>Faltbar für einfachen Transport</li><li>LED-Beleuchtung vorne und hinten</li><li>Gefederte Vorderradgabel</li></ul>',
        delivery: 'Kostenloser Versand österreichweit. Lieferzeit 7–10 Werktage.',
      },
      {
        id: 'p10',
        name: 'Retro Fat E-Bike',
        badge: '',
        category: 'Mountain E-Bikes',
        description: 'Stylisches Retro-Design trifft auf 4.0" Fat Tires und kräftigem Motor.',
        price: 'auf Anfrage',
        image: 'uploads/etb-retro-fatbike.jpg',
        specs: ['Fat Tire', 'Retro', '750W', '45 km/h'],
        specsTable: [
          { label: 'Reifengröße', value: '20" × 4.0 Fat Tire' },
          { label: 'Motor', value: '750W Mittelmotor' },
          { label: 'Höchstgeschwindigkeit', value: '45 km/h' },
          { label: 'Akku', value: '48V / 20Ah' },
          { label: 'Design', value: 'Retro-Motorrad-Stil' },
          { label: 'Beleuchtung', value: 'LED Frontscheinwerfer' },
        ],
        details: '<ul><li>Retro-Motorrad-Design mit modernem Antrieb</li><li>Großer LED-Frontscheinwerfer</li><li>Bequemer Doppel-Sattel</li><li>Vollgefedert</li></ul>',
        delivery: 'Lieferung frei Haus österreichweit. Lieferzeit 7–10 Werktage.',
      },
      {
        id: 'p11',
        name: 'Elektro-Minicar L6e',
        badge: '',
        category: 'E-Seniorenmobil',
        description: 'Vollkabiniertes 4-rädriges Elektromobil. Witterungsgeschützt, StVO-zugelassen.',
        price: 'auf Anfrage',
        image: 'uploads/etb-eauto-side.jpg',
        specs: ['45 km/h', '4-rädrig', 'Kabine', 'L6e'],
        specsTable: [
          { label: 'Höchstgeschwindigkeit', value: '45 km/h' },
          { label: 'Antrieb', value: '4-rädrig, elektrisch' },
          { label: 'Reichweite', value: 'bis 80 km' },
          { label: 'Kabine', value: 'vollständig geschlossen' },
          { label: 'Zulassung', value: 'L6e / L7e' },
          { label: 'Sitzplätze', value: '2' },
        ],
        details: '<ul><li>Vollständig geschlossene Kabine mit Windschutzscheibe</li><li>Heizung erhältlich</li><li>Türen mit Fenster</li><li>Zugelassen für öffentlichen Straßenverkehr</li></ul>',
        delivery: 'Lieferung und persönliche Einweisung in Graz. Termin nach Vereinbarung.',
      },
      {
        id: 'p12',
        name: 'Bikely Lithium Akku 48V 24Ah',
        badge: '',
        category: 'Akkus',
        subcategory: 'sub-bat-li',
        description: 'Bikely Electric Scooter Lithium Batterie 48V 24Ah. Passend für TailG und Bikely-Modelle.',
        price: 'auf Anfrage',
        image: 'uploads/etb-akku-li-48v-2.jpg',
        specs: ['48V', '24Ah', 'Lithium', 'E-Scooter'],
        specsTable: [
          { label: 'Technologie', value: 'Lithium-Ionen' },
          { label: 'Spannung', value: '48V' },
          { label: 'Kapazität', value: '24Ah / 1152Wh' },
          { label: 'Entladestrom', value: 'max. 40A' },
          { label: 'Kompatibilität', value: 'TailG, Bikely E-Scooter' },
          { label: 'BMS-Schutz', value: 'Ja' },
        ],
        details: '<ul><li>Original Bikely Ersatzakku</li><li>BMS-Schutz gegen Überspannung und Tiefentladung</li><li>Passgenau für alle Bikely Modelle</li></ul>',
        delivery: 'Kostenloser Versand. Lieferzeit 3–5 Werktage.',
      },
      {
        id: 'p13',
        name: 'Bikely E-Chopper HL 6.0',
        badge: 'Neu',
        category: 'E-Scooter 45 km/h',
        description: 'Kraftvoller Chopper-style E-Moped mit Harley-Silhouette. 3000W, 45 km/h, Straßenzulassung.',
        price: '€2.599,00',
        image: 'uploads/etb-chopper-black.jpg',
        images: ['uploads/etb-chopper-black.jpg', 'uploads/etb-chopper-black-side.jpg', 'uploads/etb-chopper-red.jpg'],
        specs: ['45 km/h', '2000W', 'Chopper-Style', 'StVO'],
        specsTable: [
          { label: 'Höchstgeschwindigkeit', value: '45 km/h' },
          { label: 'Motor', value: '2000W BLDC' },
          { label: 'Akku', value: '60V / 20Ah Lithium' },
          { label: 'Reichweite', value: 'bis 60 km' },
          { label: 'Zulassung', value: 'L3e, StVO-konform' },
          { label: 'Führerschein', value: 'Klasse A1 oder AM' },
          { label: 'Bremsen', value: 'Hydraulische Scheibenbremsen' },
          { label: 'Reifen', value: '140/70-12 vorne und hinten' },
        ],
        details: '<ul><li>Harley-Davidson Chopper-Silhouette im Elektromotorrad</li><li>Vollständige österreichische Straßenzulassung</li><li>EEC-zertifiziert</li><li>LED-Scheinwerfer rundherum</li><li>Alarmanlage inklusive</li><li>Erhältlich in Schwarz und Rot</li></ul>',
        delivery: 'Lieferung frei Haus österreichweit. Persönliche Einweisung und Probefahrt in Graz.',
      },
      {
        id: 'p14',
        name: 'Ape Ryder BABOON',
        badge: '',
        category: 'City E-Bikes',
        description: 'Retro Fat-Bike mit 20" × 4.5" Kenda-Reifen, TEKTRO Hydraulikbremsen und Dual-Suspension. 48–96 km Reichweite.',
        price: '€1.490,00',
        image: 'uploads/etb-ape-ryder-tan.jpg',
        specs: ['4.5" Fat Tire', '48V 20Ah', 'bis 96 km', 'TEKTRO Hydraulik'],
        specsTable: [
          { label: 'Akku', value: '48V / 20Ah' },
          { label: 'Geschwindigkeit', value: '32 km/h (20 mph)' },
          { label: 'Reichweite', value: '48–96 km (30–60 Meilen)' },
          { label: 'Reifen', value: '20" × 4.5" Kenda Fat Tire' },
          { label: 'Räder', value: '20" Aluminium' },
          { label: 'Schaltung', value: 'Shimano TX50, 7-Gang' },
          { label: 'Bremsen', value: 'TEKTRO Hydraulisch' },
          { label: 'Federung', value: 'Doppelte Vorderrad- & einfache Hinterradfederung' },
          { label: 'Display', value: 'M5, LCD-Mittelanzeige' },
          { label: 'Rahmen', value: 'Durchstiegrahmen (Straddle Type)' },
          { label: 'Frontlicht', value: '48V LED' },
          { label: 'Rücklicht', value: 'LED-Bremslicht' },
          { label: 'Maße', value: '106 × 165 × 104 cm' },
        ],
        details: '<ul><li>All-Terrain Fat-Bike — Stadt, Strand, Trail</li><li>TEKTRO Hydraulikbremsen für maximale Bremsleistung</li><li>Dual-Suspension für komfortables Fahren auf jedem Untergrund</li><li>Pro Wheel Kurbelgarnitur PRO-546PP-3</li><li>CE-zertifiziert, führerscheinfrei</li></ul>',
        delivery: 'Lieferung frei Haus österreichweit. Lieferzeit 7–10 Werktage.',
      },
      {
        id: 'p25',
        name: 'Ape Ryder GIBBON',
        badge: 'Premium',
        category: 'City E-Bikes',
        description: 'Premium Fat-Bike mit 500W Motor, 48V 20Ah Akku und bis 96 km Reichweite. TEKTRO Hydraulik, Dual-Suspension.',
        price: '€1.890,00',
        image: 'uploads/etb-ape-ryder-black.jpg',
        specs: ['500W', '4.5" Fat Tire', 'bis 96 km', 'Premium'],
        specsTable: [
          { label: 'Motor', value: '500W' },
          { label: 'Akku', value: '48V / 20Ah' },
          { label: 'Geschwindigkeit', value: '32 km/h (20 mph)' },
          { label: 'Reichweite', value: '48–96 km (30–60 Meilen)' },
          { label: 'Reifen', value: '20" × 4.5" Kenda Fat Tire' },
          { label: 'Räder', value: '20" Aluminium' },
          { label: 'Schaltung', value: 'Shimano TX50, 7-Gang' },
          { label: 'Bremsen', value: 'TEKTRO Hydraulisch' },
          { label: 'Federung', value: 'Dual Front & Single Back Suspension' },
          { label: 'Display', value: 'M5, LCD-Mittelanzeige' },
          { label: 'Rahmen', value: 'Straddle Type' },
          { label: 'Maße', value: '106 × 165 × 104 cm' },
        ],
        details: '<ul><li>500W Motor für kraftvolle Fahrunterstützung</li><li>All-Terrain Fat-Bike — Stadt, Strand, Offroad</li><li>TEKTRO Hydraulikbremsen</li><li>Dual-Suspension für maximalen Fahrkomfort</li><li>CE-zertifiziert, führerscheinfrei</li></ul>',
        delivery: 'Lieferung frei Haus österreichweit. Lieferzeit 7–10 Werktage.',
      },
      {
        id: 'p15',
        name: 'Dreirad E-Mobil',
        badge: '',
        category: 'E-Seniorenmobil',
        description: 'Stabiles offenes Elektro-Dreirad. Einfaches Ein- und Aussteigen, ideal für Senioren.',
        price: 'auf Anfrage',
        image: 'uploads/etb-dreirad-3q.png',
        images: ['uploads/etb-dreirad-3q.png', 'uploads/etb-dreirad-side.png', 'uploads/etb-dreirad-front.png'],
        specs: ['3-rädrig', '25 km/h', 'Vordersitz', 'CE'],
        specsTable: [
          { label: 'Antrieb', value: '3-rädrig, elektrisch' },
          { label: 'Höchstgeschwindigkeit', value: '25 km/h' },
          { label: 'Motor', value: '800W BLDC' },
          { label: 'Akku', value: '60V / 20Ah Lithium' },
          { label: 'Reichweite', value: 'bis 50 km' },
          { label: 'Rückwärtsgang', value: 'Ja' },
          { label: 'Einstiegshöhe', value: 'niedrig, barrierefrei' },
          { label: 'Gepäckkorb', value: 'vorne, integriert' },
        ],
        details: '<ul><li>Stabiles 3-Rad-Design für maximale Sicherheit</li><li>Niedriger Einstieg für einfaches Auf- und Absteigen</li><li>Rückwärtsgang für enge Stellen</li><li>Doppel-Sitz mit Rückenlehne</li><li>Frontkorb für Einkäufe</li><li>EEC/CE-zertifiziert</li></ul>',
        delivery: 'Lieferung frei Haus, 7–14 Werktage. Probefahrt und Einweisung in Graz.',
      },
      {
        id: 'p16',
        name: 'Kabinenmobil X3 Kuber',
        badge: 'Premium',
        category: 'Kabinenroller',
        description: 'Vollüberdachtes 3-rad Elektromobil mit Windschutzscheibe und Seitenschutz. Wetterfest.',
        price: 'auf Anfrage',
        image: 'uploads/etb-kabinenmobil-x3.png',
        specs: ['Kabine', '3-rädrig', '25 km/h', 'wetterfest'],
        specsTable: [
          { label: 'Antrieb', value: '3-rädrig, elektrisch' },
          { label: 'Höchstgeschwindigkeit', value: '25 km/h' },
          { label: 'Reichweite', value: 'bis 60 km' },
          { label: 'Überdachung', value: 'vollständig, wetterfest' },
          { label: 'Windschutzscheibe', value: 'Ja, klappbar' },
          { label: 'Sitzplätze', value: '2 (Fahrer + Beifahrer)' },
          { label: 'Rückwärtsgang', value: 'Ja' },
          { label: 'Zulassung', value: 'CE/EEC' },
        ],
        details: '<ul><li>Vollüberdachte Kabine mit Dach und Seitenscheiben</li><li>Klappbare Windschutzscheibe</li><li>Doppelbesetzung möglich</li><li>Rückwärtsgang und niedriger Einstieg</li><li>Ideal für Regen und Kälte</li><li>Ladekontrollanzeige am Armaturenbrett</li></ul>',
        delivery: 'Lieferung und Einweisung in Graz. Terminvereinbarung erforderlich.',
      },
      {
        id: 'p17',
        name: 'RKS XR-6 Shimano',
        badge: '',
        category: 'Mountain E-Bikes',
        description: 'Sportliches 27.5" Mountain E-Bike mit 4.0" Fat Tires, Shimano 7-Gang und LCD-Display.',
        price: '€890,00',
        image: 'uploads/etb-rks-xr-fat.png',
        specs: ['27.5" Rahmen', '4.0" Reifen', 'Shimano 7G', '25 km/h'],
        specsTable: [
          { label: 'Motor', value: '250–600W' },
          { label: 'Akku', value: '48V / 10Ah' },
          { label: 'Reichweite', value: '35–45 km' },
          { label: 'Ladezeit', value: '4–6 Stunden' },
          { label: 'Höchstgeschwindigkeit', value: '25 km/h' },
          { label: 'Rahmen', value: '27.5 Zoll Aluminium' },
          { label: 'Reifen', value: '26 × 4.0' },
          { label: 'Felge', value: '26 Zoll Magnesium' },
          { label: 'Schaltung', value: 'Shimano 7-Gang' },
          { label: 'Bremsen', value: 'Scheibenbremsen vorne & hinten' },
          { label: 'Display', value: 'Integriertes LCD' },
          { label: 'Gewicht', value: '32 kg' },
        ],
        details: '<ul><li>Ergonomischer Sattel und Griffe</li><li>Einstellbare Federgabel</li><li>Licht, Reflektoren, Hupe, USB-Port serienmäßig</li><li>Batterie mit Sicherheitsschloss</li><li>CE-zertifiziert, führerscheinfrei ab 14 Jahren</li></ul>',
        delivery: 'Kostenloser Versand österreichweit. Lieferzeit 5–7 Werktage.',
      },
      {
        id: 'p18',
        name: 'Bikely Lithium Akku 60V 78Ah',
        badge: 'Profi',
        category: 'Akkus',
        subcategory: 'sub-bat-li',
        description: 'Hochleistungs-Akku 60V 78Ah — 4.680 Wh Kapazität für Langstrecke und Heavy-Duty E-Mopeds.',
        price: 'auf Anfrage',
        image: 'uploads/etb-akku-li-60v-78ah.jpg',
        specs: ['60V', '78Ah', '4.680Wh', 'max 100A'],
        specsTable: [
          { label: 'Technologie', value: 'Lithium-Ionen' },
          { label: 'Spannung', value: '60V (17S)' },
          { label: 'Kapazität', value: '78Ah / 4.680Wh' },
          { label: 'Ladespan­nung', value: '71,4V / 8A' },
          { label: 'Entladestrom', value: '50A / max. 100A' },
          { label: 'BMS-Schutz', value: 'Überspannung, Tiefentladung, Temperatur' },
          { label: 'Anschluss', value: 'XT90 / Anderson' },
          { label: 'Gewicht', value: 'ca. 12 kg' },
        ],
        details: '<ul><li>Maximale Reichweite durch 4.680 Wh Kapazität</li><li>Passend für TailG, Bikely 45 km/h Modelle und Citycoco Chopper</li><li>BMS mit Überlade-, Tiefentlade- und Temperaturschutz</li><li>Original Bikely geprüft und zertifiziert</li><li>Integrierter LED-Ladezustandsanzeiger</li></ul>',
        delivery: 'Kostenloser Versand. Lieferzeit 5–7 Werktage.',
      },
      {
        id: 'p23',
        name: 'FALCON 3400 E-Moped',
        badge: '',
        category: 'E-Scooter 45 km/h',
        description: 'Sportliches E-Moped 45 km/h mit modernem Design und starkem Antrieb. CE/EEC Straßenzulassung.',
        price: '€1.690,00',
        image: 'uploads/etb-moped-city.jpg',
        specs: ['45 km/h', 'CE/EEC', 'Straßenzulassung'],
        specsTable: [
          { label: 'Motor', value: '72V 3000W' },
          { label: 'Höchstgeschwindigkeit', value: '45 km/h' },
          { label: 'Reichweite', value: 'bis 60 km' },
          { label: 'Akkukapazität', value: '72V 20Ah' },
          { label: 'Batterietyp', value: 'Li-Ion / Bleigel' },
          { label: 'Ladezeit', value: '6–7 Stunden' },
          { label: 'Ladegerät', value: '72V / 3A' },
          { label: 'Reifen', value: '12 Zoll Tubeless (vorne & hinten)' },
          { label: 'Bremsen', value: 'Scheibenbremsen' },
          { label: 'Max. Zuladung', value: '236 kg' },
          { label: 'Steigung', value: '20%' },
          { label: 'Gewicht', value: '95 kg' },
          { label: 'Ausstattung', value: '2 Rückspiegel, Alarmanlage' },
          { label: 'Betriebskosten', value: 'ca. €1,00 / 100 km' },
          { label: 'Zulassung', value: 'CE/EEC · L3e · StVO-konform' },
          { label: 'Führerschein', value: 'Klasse A1 oder AM' },
        ],
        details: '<ul><li>Kraftvoller 3000W / 72V Motor</li><li>Sportliches Design mit maximaler Zuladung (236 kg)</li><li>Alarmanlage serienmäßig</li><li>Extrem günstige Betriebskosten: ca. €1,00 / 100 km</li><li>CE/EEC zertifiziert, vollständige Straßenzulassung</li><li>Vormontierte Lieferung (ca. 90%)</li><li>Förderfähig: bis zu €600 E-Mobilitätsbonus (eRide 2025)</li></ul>',
        delivery: 'Lieferung frei Haus österreichweit. Lieferzeit 5–7 Werktage.',
      },
      {
        id: 'p24',
        name: 'Bikely E-Chopper Blake',
        badge: 'Premium',
        category: 'E-Scooter 45 km/h',
        description: 'Premium Chopper E-Moped mit 3000W und bis 120 km Reichweite. Das Flaggschiff der Bikely Chopper-Linie.',
        price: '€2.999,00',
        image: 'uploads/etb-chopper-black-side.jpg',
        images: ['uploads/etb-chopper-black-side.jpg', 'uploads/etb-chopper-black.jpg'],
        specs: ['45 km/h', '3000W', 'bis 120 km', 'Premium'],
        specsTable: [
          { label: 'Motor', value: '60V 3000W' },
          { label: 'Höchstgeschwindigkeit', value: '45 km/h' },
          { label: 'Reichweite', value: 'bis 120 km' },
          { label: 'Akkukapazität', value: '72V 20Ah' },
          { label: 'Batterietyp', value: 'Li-Ion / Bleigel' },
          { label: 'Ladezeit', value: '6–7 Stunden' },
          { label: 'Ladegerät', value: '60V / 3A' },
          { label: 'Reifen', value: 'Vorderrad 17 Zoll · Hinterrad 13 Zoll Tubeless' },
          { label: 'Bremsen', value: 'Scheibenbremsen / Trommelbremsen' },
          { label: 'Max. Zuladung', value: '149 kg' },
          { label: 'Steigung', value: '20%' },
          { label: 'Gewicht', value: '96 kg' },
          { label: 'Zulassung', value: 'CE/EEC · L3e · StVO-konform' },
          { label: 'Führerschein', value: 'Klasse A1 oder AM' },
        ],
        details: '<ul><li>Premium-Variante der Bikely Chopper-Linie</li><li>3000W Motor für kraftvollen Antrieb</li><li>Bis 120 km Reichweite</li><li>Chopper-Design mit breiten Reifen</li><li>CE/EEC zertifiziert, vollständige Straßenzulassung</li><li>Förderfähig: bis zu €600 E-Mobilitätsbonus (eRide 2025)</li></ul>',
        delivery: 'Lieferung frei Haus österreichweit. Persönliche Einweisung in Graz möglich.',
      },
      {
        id: 'p19',
        name: 'KUBA GREE08 E-Scooter',
        badge: '',
        category: 'E-Scooter 25 km/h',
        description: 'Kompaktes Stadt-Elektromoped mit auswechselbarem Akku und großer Reichweite. 25–45 km/h, CE/EEC.',
        price: '€749,00',
        image: 'uploads/etb-moped-city-silver.jpg',
        specs: ['25–45 km/h', 'bis 240 km', '600W', 'CE/EEC'],
        specsTable: [
          { label: 'Motor', value: '600W / 72–60V' },
          { label: 'Höchstgeschwindigkeit', value: '25–45 km/h' },
          { label: 'Reichweite', value: 'max. bis 240 km' },
          { label: 'Akkukapazität', value: '20–78Ah Li-Ion (tragbar)' },
          { label: 'Ladezeit', value: '6–8 Stunden' },
          { label: 'Reifen', value: '3.0 × 10 Tubeless' },
          { label: 'Bremsen', value: 'Scheibenbremse vorne, Trommelbremse hinten' },
          { label: 'Lichttechnik', value: 'Stand-, Abblend-, Fernlicht + LED Rücklicht' },
          { label: 'Max. Zuladung', value: '213 kg' },
          { label: 'Steigung', value: '22%' },
          { label: 'Ausstattung', value: '2 Spiegel, Hupe, USB-Port, Alarm' },
          { label: 'Maße', value: '1710 × 730 × 1155 mm' },
          { label: 'Gewicht', value: '70 kg' },
        ],
        details: '<ul><li>CE/EEC zertifiziert, auf Radweg zugelassen</li><li>Auswechselbarer Akku — laden am Fahrzeug oder zu Hause</li><li>Stahlfelgen für langlebigen Betrieb</li><li>Diebstahlalarmanlage inklusive</li><li>Förderfähig: €600 E-Mobilitätsbonus (L1e, eRide 2025)</li><li>Vormontierte Lieferung (ca. 90%)</li></ul>',
        delivery: 'Kostenloser Versand österreichweit. Lieferzeit 5–7 Werktage.',
      },
      {
        id: 'p20',
        name: 'KUBA BLUES E-Moped',
        badge: '',
        category: 'E-Scooter 25 km/h',
        description: 'Kraftvolles 1200W E-Moped mit 25 km/h Zulassung. Wählbarer Akku: 40Ah oder 78Ah Reichweite.',
        price: '€990,00',
        image: 'uploads/etb-moped-city-silver-front.jpg',
        specs: ['25 km/h', '1200W', 'bis 225 km', 'CE/EEC'],
        specsTable: [
          { label: 'Motor', value: '1200W' },
          { label: 'Höchstgeschwindigkeit', value: '25 km/h (gedrosselt)' },
          { label: 'Reichweite', value: '60V 40Ah: bis 110 km · 60V 78Ah: bis 225 km' },
          { label: 'Batterietyp', value: 'Li-Ion (wählbar: 40Ah oder 78Ah)' },
          { label: 'Ladegerät', value: '60V (abhängig vom Akkutyp)' },
          { label: 'Ladezeit', value: '6–8 Stunden' },
          { label: 'Reifen', value: '3.50–10 Tubeless' },
          { label: 'Bremsen', value: 'Scheibenbremse / Trommelbremse' },
          { label: 'Max. Zuladung', value: '225 kg' },
          { label: 'Steigung', value: '20%' },
          { label: 'Ausstattung', value: '2 Spiegel, Hupe, USB-Port' },
          { label: 'Maße', value: '1220–1650 × 660 mm' },
          { label: 'Gewicht', value: '90 kg' },
        ],
        details: '<ul><li>CE/EEC zertifiziert, auf Radweg zugelassen</li><li>Führerscheinfrei (L1e) mit 25 km/h Drosselung</li><li>Akku-Variante wählbar für maximale Reichweite</li><li>Auswechselbarer Akku — laden am Fahrzeug oder zu Hause</li><li>Sofort abholbar in Graz</li><li>Förderfähig: €600 E-Mobilitätsbonus (eRide 2025)</li></ul>',
        delivery: 'Kostenloser Versand österreichweit oder sofortige Abholung in Graz. Lieferzeit 5–7 Werktage.',
      },
      {
        id: 'p21',
        name: 'RKS CD35 DUAL SUSPENSION',
        badge: '',
        category: 'Mountain E-Bikes',
        description: 'Vollgefedertes 27.5" Mountain E-Bike mit Shimano-Schaltung und LCD-Display. Bremsvariante wählbar.',
        price: '€790,00',
        image: 'uploads/etb-rks-xr-fat.png',
        specs: ['Dual Suspension', '250W', '25 km/h', '27.5 Zoll'],
        specsTable: [
          { label: 'Motor', value: '250–600W' },
          { label: 'Akku', value: '36V / 10Ah' },
          { label: 'Reichweite', value: 'bis 45 km' },
          { label: 'Ladezeit', value: '4–6 Stunden' },
          { label: 'Höchstgeschwindigkeit', value: '25 km/h' },
          { label: 'Rahmen', value: '27.5 Zoll Aluminium' },
          { label: 'Reifen', value: '27.5 × 1.95' },
          { label: 'Felge', value: '27.5 Zoll' },
          { label: 'Schaltung', value: 'Shimano SL-TX50LN' },
          { label: 'Bremsen', value: 'Scheibenbremsen (opt. Hydraulik +€160)' },
          { label: 'Display', value: 'LCD integriert' },
          { label: 'Gewicht', value: '22 kg' },
        ],
        details: '<ul><li>Dual Suspension: doppelte Vorderrad- & Hinterradfederung</li><li>Batterie mit Sicherheitsschloss</li><li>Option: mit Hydraulikbremse (+€160) wählbar</li><li>Licht, Reflektoren, Hupe serienmäßig</li><li>CE-zertifiziert, führerscheinfrei ab 14 Jahren</li></ul>',
        delivery: 'Kostenloser Versand österreichweit. Lieferzeit 5–7 Werktage.',
      },
      {
        id: 'p22',
        name: 'E-Motorrad "Mars" 100 km/h',
        badge: 'Highlight',
        category: 'E-Motorrad',
        description: 'Vollwertiges E-Motorrad mit 6000W und 100 km/h. CE/EEC Straßenzulassung, Ratenzahlung möglich.',
        price: '€3.999,00',
        image: 'uploads/etb-moped-white-45.png',
        specs: ['100 km/h', '6000W', 'CE/EEC', 'Straßenzulassung'],
        specsTable: [
          { label: 'Motor', value: '6000W' },
          { label: 'Höchstgeschwindigkeit', value: '100 km/h' },
          { label: 'Zulassung', value: 'CE/EEC, Straßenzulassung' },
          { label: 'Führerschein', value: 'Klasse A / A2' },
          { label: 'Lieferzeit', value: '4–14 Werktage' },
          { label: 'Ratenzahlung', value: 'möglich' },
        ],
        details: '<ul><li>Vollwertiges Elektromotorrad mit 100 km/h Topspeed</li><li>CE/EEC zertifiziert, vollständige Straßenzulassung</li><li>Ratenzahlung auf Anfrage möglich</li><li>Lieferzeit 8–14 Werktage (Online Only)</li><li>Förderfähig: bis zu €1.800 E-Mobilitätsbonus (L3e, eRide 2025)</li></ul>',
        delivery: 'Lieferung frei Haus österreichweit. Lieferzeit 8–14 Werktage. Probefahrt in Graz nach Vereinbarung.',
      },
    ],
  },
  usp: {
    eyebrow: 'Warum e-techbike.at?',
    title: 'Was uns unterscheidet',
    items: [
      { id: 'u1', title: 'Direktimport-Preise', description: 'Kein Zwischenhändler. Wir importieren direkt vom Hersteller und geben die volle Ersparnis weiter.' },
      { id: 'u2', title: '2 Jahre Garantie', description: 'Herstellergarantie auf alle Fahrzeuge und Akkus. Reparatur und Ersatzteile direkt bei uns.' },
      { id: 'u3', title: 'Persönliche Beratung', description: 'Testfahrten und Beratung vor Ort in Graz. Terminvereinbarung per Anruf oder E-Mail.' },
      { id: 'u4', title: 'Schnelle Lieferung', description: 'Österreichweiter Versand in 5–7 Werktagen. Vollversichert und mit Sendungsverfolgung.' },
      { id: 'u5', title: 'Förderungsberatung', description: 'Bis zu €1.800 staatliche Förderung. Wir begleiten Sie kostenlos durch die Beantragung.' },
      { id: 'u6', title: 'Werkstatt & Service', description: 'Vollständige Werkstatt in Graz. Wartung, Zubehör und Ersatzteile immer verfügbar.' },
    ],
  },
  news: {
    eyebrow: 'Neuigkeiten',
    title: 'Aktuell bei e-techbike.at',
    items: [
      {
        id: 'n1', date: '2026-05-01',
        title: 'Bis zu €1.800 E-Mobilitätsförderung — jetzt sichern!',
        body: 'Der Staat fördert E-Motorräder mit bis zu €1.800, E-Mopeds mit €1.200 und E-Klappräder mit €500. Gültig bis 31.03.2026 oder solange das Förderbudget reicht. Wir helfen bei der Antragstellung.',
      },
      {
        id: 'n2', date: '2026-04-15',
        title: 'Neue RKS E-Bike Modelle 2026 eingetroffen',
        body: 'Die neueste RKS-Kollektion ist da! Klappräder, City-Bikes und Fat Bikes — jetzt im Showroom in Graz vorbeikommen und Probefahrt vereinbaren.',
      },
      {
        id: 'n3', date: '2026-03-20',
        title: 'Werkstatt für alle E-Bike Marken geöffnet',
        body: 'Unsere Werkstatt in der Ghegagasse 29 ist für alle E-Bike und E-Scooter Marken geöffnet. Wartung, Ersatzteile und Zubehör direkt vor Ort.',
      },
    ],
  },
  contact: {
    title: 'Besuchen Sie uns in Graz.',
    subtitle: 'Persönliche Beratung, Testfahrten und direkte Abholung. Wir freuen uns auf Ihren Besuch.',
    email: 'graz@bikelyshop.at',
    phone: '+43 664 7372 6965',
    address: 'Ghegagasse 29, 8020 Graz, Österreich',
    whatsapp: '+436647372965',
    mapSrc: 'https://maps.google.com/maps?q=Ghegagasse+29,+8020+Graz,+Austria&output=embed&z=16',
    formEnabled: true,
  },
  whatsapp: {
    enabled: true,
    number: '+436647372965',
    message: 'Hallo! Ich interessiere mich für Ihre E-Bikes und möchte eine Beratung anfragen.',
  },
  footer: {
    brand: 'e-techbike.at',
    tagline: 'Direktimporteur für Premium-Elektromobilität',
    description: 'Österreichs Direktimporteur für Premium-Elektromobilität. Beratung, faire Preise, voller Service in Graz.',
    cols: [
      {
        title: 'Sortiment',
        links: [
          { label: 'E-Bikes', href: '#products' },
          { label: 'E-Mopeds', href: '#products' },
          { label: 'E-Scooter', href: '#products' },
          { label: 'Seniorenmobile', href: '#products' },
          { label: 'Batterien & Akkus', href: '#products' },
        ],
      },
      {
        title: 'Service',
        links: [
          { label: 'Über uns', href: '#location' },
          { label: 'Förderungen', href: '#foerderung' },
          { label: 'Werkstatt', href: '#location' },
          { label: 'Akku-Pflege', href: '#location' },
          { label: 'Kontakt', href: '#location' },
        ],
      },
      {
        title: 'Rechtliches',
        links: [
          { label: 'AGB', href: '/agb' },
          { label: 'Datenschutz', href: '/datenschutz' },
          { label: 'Impressum', href: '/impressum' },
        ],
      },
    ],
    links: [
      { label: 'AGB', href: '/agb' },
      { label: 'Datenschutz', href: '/datenschutz' },
      { label: 'Impressum', href: '/impressum' },
    ],
    copyright: '© 2026 e-techbike.at — made with love by RFI-IRFOS',
  },
}
