import type { SiteContent } from './content'

export const defaultContent: SiteContent = {
  meta: {
    title: 'e-techbike.at — Elektromobilität Graz',
    description: 'Premium E-Bikes, E-Scooter und E-Motorräder. Direktimporteur in Graz. 2 Jahre Garantie.',
    primaryColor: '#0099CC',
    accentColor: '#B3E600',
    font: "system-ui, -apple-system, 'Segoe UI', sans-serif",
  },
  nav: {
    logo: 'uploads/etb-logo.jpg',
    brand: 'e-techbike.at',
    links: [
      { label: 'Sortiment', href: '#products' },
      { label: 'Förderungen', href: '#foerderung' },
      { label: 'Standort', href: '#location' },
      { label: 'Neuigkeiten', href: '#news' },
    ],
    phone: '+43 664 7372 6965',
    ctaLabel: 'Beratung anfragen',
    ctaHref: '#location',
  },
  hero: {
    tag: 'Direktimporteur · Graz · Österreich',
    headline: 'Elektro&shy;mobilität.<br><span>Jetzt.</span>',
    subheadline: 'Premium E-Bikes, E-Scooter und E-Motorräder — direkt vom Hersteller, mit voller Garantie und persönlicher Beratung in Graz.',
    ctaLabel: 'Sortiment entdecken',
    ctaHref: '#products',
    ctaSecLabel: 'Beratung anfragen',
    ctaSecHref: '#location',
    image: 'uploads/etb-rks-mx25.jpg',
    bgX: 50,
    bgY: 40,
    minHeight: 680,
  },
  trust: {
    items: [
      { id: 't1', icon: 'delivery', bold: '5–7 Tage', text: 'Versand österreichweit' },
      { id: 't2', icon: 'shield', bold: '2 Jahre', text: 'Herstellergarantie' },
      { id: 't3', icon: 'tag', bold: 'Direktimport', text: 'kein Aufschlag' },
      { id: 't4', icon: 'location', bold: 'Beratung', text: 'in Graz' },
    ],
  },
  categories: {
    eyebrow: 'Sortiment',
    title: 'Für jeden das richtige Fahrzeug',
    items: [
      {
        id: 'cat-bikes',
        name: 'E-Bikes',
        sub: 'Faltrad · City · Mountain',
        image: 'uploads/etb-rks-faltbike.jpg',
        subcategories: [
          { id: 'sub-bike-falt', name: 'Faltrad E-Bike', image: 'uploads/etb-rks-faltbike.jpg', description: 'Kompakt, leicht, alltagstauglich' },
          { id: 'sub-bike-city', name: 'City & Trekking', image: 'uploads/etb-rks-mx25-life.jpg', description: 'Komfortabel für Stadt und Tour' },
          { id: 'sub-bike-fat', name: 'Mountain & Fat Bike', image: 'uploads/etb-rks-fat-black.jpg', description: 'Geländetauglich und kraftvoll' },
        ],
      },
      {
        id: 'cat-moped',
        name: 'E-Mopeds',
        sub: '25 km/h · 45 km/h',
        image: 'uploads/etb-tailg-runner.png',
        subcategories: [
          { id: 'sub-moped-25', name: '25 km/h · L1e', image: 'uploads/etb-moped-city.jpg', description: 'Führerscheinfrei ab 16 Jahren' },
          { id: 'sub-moped-45', name: '45 km/h · L3e', image: 'uploads/etb-bikely-moped-45.jpg', description: 'Mit Motorrad-Führerschein' },
        ],
      },
      {
        id: 'cat-scooter',
        name: 'E-Scooter',
        sub: 'Führerscheinfrei · 45 km/h',
        image: 'uploads/etb-escooter.png',
        subcategories: [
          { id: 'sub-scooter-25', name: '25 km/h (führerscheinfrei)', image: 'uploads/etb-escooter.png', description: 'Ab 14 Jahren, kein Führerschein' },
          { id: 'sub-scooter-45', name: '45 km/h (Klasse AM)', image: 'uploads/etb-scooter-45-red.png', description: 'Mehr Speed, Führerschein AM' },
        ],
      },
      {
        id: 'cat-senior',
        name: 'Seniorenmobile',
        sub: 'Komfort & Sicherheit',
        image: 'uploads/etb-kuba-grape.png',
        subcategories: [
          { id: 'sub-senior-kab', name: 'Kabinenroller', image: 'uploads/etb-kuba-grape-v2.png', description: 'Überdacht, wetterfest, sicher' },
          { id: 'sub-senior-drei', name: 'Dreiräder & Elektromobile', image: 'uploads/etb-eauto-side.jpg', description: 'Stabil und komfortabel' },
        ],
      },
      {
        id: 'cat-bat',
        name: 'Batterien & Akkus',
        sub: 'Bleigel · Lithium',
        image: 'uploads/etb-akku-48v.jpg',
        subcategories: [
          { id: 'sub-bat-agm', name: 'Bleigel / AGM', image: 'uploads/etb-akku-48v.jpg', description: 'Robust und wartungsarm' },
          { id: 'sub-bat-li', name: 'Lithium', image: 'uploads/etb-akku-li-48v.jpg', description: 'Leicht, leistungsstark, langlebig' },
        ],
      },
      {
        id: 'cat-parts',
        name: 'Ersatzteile',
        sub: 'Zubehör & Service',
        image: 'uploads/etb-akku-48v.jpg',
      },
    ],
  },
  products: {
    title: 'Bestseller',
    tabs: ['Alle', 'E-Bikes', 'E-Mopeds', 'E-Scooter', 'Senioren', 'Batterien'],
    items: [
      {
        id: 'p1',
        name: 'RKS Falt-E-Bike Pro',
        badge: 'Bestseller',
        category: 'E-Bikes',
        subcategory: 'sub-bike-falt',
        description: 'Kompaktes Falt-E-Bike für Stadt und Alltag. Shimano 7-Gang, 80 km Reichweite.',
        price: 'ab €899',
        image: 'uploads/etb-rks-faltbike.jpg',
        specs: ['48V', '20Ah', '80 km', 'Shimano 7G'],
        specsTable: [
          { label: 'Spannung', value: '48V' },
          { label: 'Kapazität', value: '20Ah' },
          { label: 'Reichweite', value: 'bis 80 km' },
          { label: 'Motor', value: '250W Heckmotor' },
          { label: 'Schaltung', value: 'Shimano 7-Gang' },
          { label: 'Höchstgeschwindigkeit', value: '25 km/h' },
          { label: 'Rahmen', value: 'Aluminium, faltbar' },
          { label: 'Gewicht', value: '~22 kg' },
        ],
        details: '<ul><li>CE-zertifiziert nach EU-Richtlinien</li><li>Integriertes LED-Beleuchtungssystem</li><li>Hydraulische Scheibenbremsen</li><li>Luftbereifung 20 Zoll</li><li>Inkl. Ladegerät und Werkzeug</li></ul>',
        delivery: 'Kostenloser Versand österreichweit. Lieferzeit 5–7 Werktage. Abholung in Graz nach Terminvereinbarung möglich.',
      },
      {
        id: 'p2',
        name: 'RKS MX25 PRO Faltrad',
        badge: '',
        category: 'E-Bikes',
        subcategory: 'sub-bike-falt',
        description: 'Führerscheinfreies 25 km/h Faltrad mit 250W Motor. Ideal für die Stadt.',
        price: 'ab €799',
        image: 'uploads/etb-rks-mx25.jpg',
        specs: ['25 km/h', '250W', '35–45 km', 'führerscheinfrei'],
        specsTable: [
          { label: 'Spannung', value: '36V' },
          { label: 'Kapazität', value: '10Ah' },
          { label: 'Reichweite', value: '35–45 km' },
          { label: 'Motor', value: '250W Heckmotor' },
          { label: 'Höchstgeschwindigkeit', value: '25 km/h' },
          { label: 'Führerschein', value: 'nicht erforderlich' },
          { label: 'Rahmen', value: 'Aluminium, faltbar' },
          { label: 'Reifengröße', value: '20 Zoll' },
        ],
        details: '<ul><li>Führerscheinfrei ab 14 Jahren</li><li>Keine Versicherungspflicht</li><li>Integriertes Display mit 5 Unterstützungsstufen</li><li>USB-Ladeport am Akku</li></ul>',
        delivery: 'Kostenloser Versand österreichweit. Lieferzeit 5–7 Werktage.',
      },
      {
        id: 'p3',
        name: 'TailG E-Moped Runner',
        badge: 'Beliebt',
        category: 'E-Mopeds',
        subcategory: 'sub-moped-45',
        description: 'Straßenzugelassenes E-Moped mit Topcase inklusive. 45 km/h, volle StVO-Zulassung.',
        price: 'ab €1.290',
        image: 'uploads/etb-tailg-runner-hd.png',
        specs: ['45 km/h', '60 km', 'Topcase', 'StVO'],
        specsTable: [
          { label: 'Höchstgeschwindigkeit', value: '45 km/h' },
          { label: 'Reichweite', value: 'bis 60 km' },
          { label: 'Motor', value: '2000W BLDC' },
          { label: 'Akku', value: '60V / 20Ah Lithium' },
          { label: 'Zulassung', value: 'L3e, StVO-konform' },
          { label: 'Führerschein', value: 'Klasse A1 oder AM' },
          { label: 'Topcase', value: 'inklusive, 28L' },
          { label: 'Ladezeit', value: 'ca. 6–8 Stunden' },
        ],
        details: '<ul><li>Vollständige österreichische Straßenzulassung</li><li>EEC-zertifiziert</li><li>LED-Scheinwerfer vorne und hinten</li><li>Alarmanlage inklusive</li><li>USB-Ladeanschluss</li></ul>',
        delivery: 'Lieferung frei Haus österreichweit, 5–7 Werktage. Montage und Einweisung in Graz möglich.',
      },
      {
        id: 'p4',
        name: 'Bikely ZL9 E-Scooter',
        badge: '',
        category: 'E-Scooter',
        subcategory: 'sub-scooter-25',
        description: 'Kompakter Stadtscooter, führerscheinfrei, 25 km/h, bis 45 km Reichweite.',
        price: 'ab €690',
        image: 'uploads/etb-bikely-zl9.jpg',
        specs: ['25 km/h', '45 km', 'kompakt', 'führerscheinfrei'],
        specsTable: [
          { label: 'Höchstgeschwindigkeit', value: '25 km/h' },
          { label: 'Reichweite', value: 'bis 45 km' },
          { label: 'Motor', value: '350W Heckmotor' },
          { label: 'Akku', value: '36V / 10Ah Lithium' },
          { label: 'Führerschein', value: 'nicht erforderlich' },
          { label: 'Faltsystem', value: 'Ja, kompakt' },
          { label: 'Max. Zuladung', value: '120 kg' },
          { label: 'Gewicht', value: '~14 kg' },
        ],
        details: '<ul><li>Führerscheinfrei ab 14 Jahren</li><li>IP54 Spritzwasserschutz</li><li>Doppelscheibenbremse vorne und hinten</li><li>10-Zoll-Luftreifen für komfortables Fahren</li></ul>',
        delivery: 'Kostenloser Versand. Lieferzeit 5–7 Werktage. Bereits fertig montiert.',
      },
      {
        id: 'p5',
        name: 'Lithium Akku 48V 25Ah',
        badge: '',
        category: 'Batterien & Akkus',
        subcategory: 'sub-bat-li',
        description: 'Hochleistungs-Lithium-Akku mit BMS-Schutz, 3.000+ Ladezyklen, 5 Jahre Garantie.',
        price: 'ab €599',
        image: 'uploads/etb-akku-48v.jpg',
        specs: ['48V', '25Ah', 'BMS', '3.000+ Zyklen'],
        specsTable: [
          { label: 'Technologie', value: 'Lithium-Ionen' },
          { label: 'Spannung', value: '48V' },
          { label: 'Kapazität', value: '25Ah' },
          { label: 'Anschluss', value: 'XT60 / Anderson' },
          { label: 'Ladezyklen', value: '3.000+' },
          { label: 'BMS-Schutz', value: 'Überspannung, Tiefentladung, Temperatur' },
          { label: 'Gewicht', value: '~5,5 kg' },
          { label: 'Ladezeit', value: 'ca. 5–7 Stunden' },
        ],
        details: '<ul><li>Anwendungsbereiche: E-Bikes, E-Scooter, Elektromobile, Segel- und Elektroboote, Wohnwagen, Windenergieanlagen, Solaranlagen, Weidezäune, Reha-Technik</li><li>Integriertes BMS (Battery Management System)</li><li>Temperaturschutz und Überladeschutz</li><li>5 Jahre Herstellergarantie</li></ul>',
        delivery: 'Kostenloser Versand österreichweit. Lieferzeit 3–5 Werktage.',
      },
      {
        id: 'p6',
        name: 'KUBA Grape 25 MAX',
        badge: '',
        category: 'Seniorenmobile',
        subcategory: 'sub-senior-kab',
        description: 'Überdachtes 3-rädriges Seniorenmobil mit CE/EEC-Zulassung, 25 km/h.',
        price: 'ab €1.890',
        image: 'uploads/etb-kuba-grape-v2.png',
        specs: ['25 km/h', '3-rädrig', 'Überdachung', 'CE/EEC'],
        specsTable: [
          { label: 'Höchstgeschwindigkeit', value: '25 km/h' },
          { label: 'Antrieb', value: '3-rädrig, elektrisch' },
          { label: 'Motor', value: '1200W BLDC' },
          { label: 'Akku', value: '60V / 20Ah Lithium' },
          { label: 'Reichweite', value: 'bis 60 km' },
          { label: 'Überdachung', value: 'Ja, wetterfest' },
          { label: 'Zulassung', value: 'CE/EEC, L2e' },
          { label: 'Max. Zuladung', value: '200 kg' },
        ],
        details: '<ul><li>Vollständige Witterungsschutz-Kabine</li><li>Heizung optional erhältlich</li><li>Elektrische Servolenkung</li><li>Rückfahrkamera serienmäßig</li><li>Zugelassen für öffentlichen Straßenverkehr</li></ul>',
        delivery: 'Lieferung frei Haus, 7–14 Werktage. Persönliche Einweisung und Probefahrt in Graz.',
      },
      {
        id: 'p7',
        name: 'Bleigel Akku 12V 20Ah',
        badge: '',
        category: 'Batterien & Akkus',
        subcategory: 'sub-bat-agm',
        description: 'VRLA Bleigel Deep-Cycle Batterie. Wartungsfrei, robust, vielseitig einsetzbar.',
        price: '€55,00',
        regularPrice: '€75,00',
        image: 'uploads/etb-akku-48v.jpg',
        specs: ['12V', '20Ah', 'AGM', 'Deep Cycle'],
        specsTable: [
          { label: 'Technologie', value: 'AGM / Bleigel' },
          { label: 'Spannung', value: '12V' },
          { label: 'Kapazität', value: '20Ah' },
          { label: 'Anschluss', value: 'F11 (M6)' },
          { label: 'Typ', value: 'Deep Cycle, VRLA' },
          { label: 'Wartung', value: 'wartungsfrei' },
          { label: 'Maße (B×H×T)', value: '181 × 167 × 77 mm' },
          { label: 'Gewicht', value: 'ca. 5,8 kg' },
        ],
        details: '<ul><li>Anwendungsbereiche: Reha-Technik (Rollstühle, Lifter, Seniorenmobile), E-Scooter, Elektromobile, Segel- und Elektroboote, Wohnwagen, Windenergieanlagen, Solaranlagen, Weidezäune</li><li>VRLA-versiegelt, auslaufsicher</li><li>Wartungsfreier Betrieb</li><li>UL- und CE-zertifiziert</li></ul>',
        delivery: 'Kostenloser Versand österreichweit. Lieferzeit 2–4 Werktage.',
      },
      {
        id: 'p8',
        name: 'Bikely E-Moped 45 km/h',
        badge: 'Neu',
        category: 'E-Mopeds',
        subcategory: 'sub-moped-45',
        description: 'Straßenzugelassenes E-Moped 45 km/h mit Topcase. Bikely-Design, LED rundum.',
        price: 'auf Anfrage',
        image: 'uploads/etb-bikely-moped-45.jpg',
        specs: ['45 km/h', 'Topcase', 'LED', 'StVO'],
        specsTable: [
          { label: 'Höchstgeschwindigkeit', value: '45 km/h' },
          { label: 'Motor', value: '2000W BLDC' },
          { label: 'Akku', value: '60V / 20Ah Lithium' },
          { label: 'Zulassung', value: 'L3e, StVO-konform' },
          { label: 'Führerschein', value: 'Klasse A1 oder AM' },
          { label: 'Topcase', value: 'inklusive' },
        ],
        details: '<ul><li>Vollständige österreichische Straßenzulassung</li><li>LED-Scheinwerfer, Blinker und Rückleuchten</li><li>Alarmanlage inklusive</li><li>USB-Ladeanschluss</li></ul>',
        delivery: 'Lieferung frei Haus österreichweit. Persönliche Einweisung in Graz möglich.',
      },
      {
        id: 'p9',
        name: 'RKS Fat Fold E-Bike',
        badge: '',
        category: 'E-Bikes',
        subcategory: 'sub-bike-fat',
        description: 'Faltbares Fat Bike mit 20" Ballonreifen. Perfekt für Gelände und Stadt.',
        price: 'auf Anfrage',
        image: 'uploads/etb-rks-fat-grey.png',
        specs: ['Fat Tire', 'faltbar', '250W', '25 km/h'],
        specsTable: [
          { label: 'Reifengröße', value: '20" × 4.0 Fat Tire' },
          { label: 'Motor', value: '250W Heckmotor' },
          { label: 'Höchstgeschwindigkeit', value: '25 km/h' },
          { label: 'Rahmen', value: 'Aluminium, faltbar' },
          { label: 'Bremsen', value: 'Hydraulische Scheibenbremsen' },
          { label: 'Schaltung', value: 'Shimano 7-Gang' },
        ],
        details: '<ul><li>Geländetauglich durch breite 4.0" Fat Tires</li><li>Faltbar für einfachen Transport</li><li>LED-Beleuchtung vorne und hinten</li><li>Gefederte Vorderradgabel</li></ul>',
        delivery: 'Kostenloser Versand österreichweit. Lieferzeit 7–10 Werktage.',
      },
      {
        id: 'p10',
        name: 'Retro Fat E-Bike',
        badge: '',
        category: 'E-Bikes',
        subcategory: 'sub-bike-fat',
        description: 'Stylisches Retro-Design trifft auf 4.0" Fat Tires und kräftigem Motor.',
        price: 'auf Anfrage',
        image: 'uploads/etb-retro-fatbike.jpg',
        specs: ['Fat Tire', 'Retro', '750W', '45 km/h'],
        specsTable: [
          { label: 'Reifengröße', value: '20" × 4.0 Fat Tire' },
          { label: 'Motor', value: '750W Mittelmotor' },
          { label: 'Höchstgeschwindigkeit', value: '45 km/h' },
          { label: 'Akku', value: '48V / 20Ah' },
          { label: 'Design', value: 'Retro-Motorrad-Stil' },
          { label: 'Beleuchtung', value: 'LED Frontscheinwerfer' },
        ],
        details: '<ul><li>Retro-Motorrad-Design mit modernem Antrieb</li><li>Großer LED-Frontscheinwerfer</li><li>Bequemer Doppel-Sattel</li><li>Vollgefedert</li></ul>',
        delivery: 'Lieferung frei Haus österreichweit. Lieferzeit 7–10 Werktage.',
      },
      {
        id: 'p11',
        name: 'Elektro-Minicar L6e',
        badge: '',
        category: 'Seniorenmobile',
        subcategory: 'sub-senior-drei',
        description: 'Vollkabiniertes 4-rädriges Elektromobil. Witterungsgeschützt, StVO-zugelassen.',
        price: 'auf Anfrage',
        image: 'uploads/etb-eauto-side.jpg',
        specs: ['45 km/h', '4-rädrig', 'Kabine', 'L6e'],
        specsTable: [
          { label: 'Höchstgeschwindigkeit', value: '45 km/h' },
          { label: 'Antrieb', value: '4-rädrig, elektrisch' },
          { label: 'Reichweite', value: 'bis 80 km' },
          { label: 'Kabine', value: 'vollständig geschlossen' },
          { label: 'Zulassung', value: 'L6e / L7e' },
          { label: 'Sitzplätze', value: '2' },
        ],
        details: '<ul><li>Vollständig geschlossene Kabine mit Windschutzscheibe</li><li>Heizung erhältlich</li><li>Türen mit Fenster</li><li>Zugelassen für öffentlichen Straßenverkehr</li></ul>',
        delivery: 'Lieferung und persönliche Einweisung in Graz. Termin nach Vereinbarung.',
      },
      {
        id: 'p12',
        name: 'Bikely Lithium Akku 48V 24Ah',
        badge: '',
        category: 'Batterien & Akkus',
        subcategory: 'sub-bat-li',
        description: 'Bikely Electric Scooter Lithium Batterie 48V 24Ah. Passend für TailG und Bikely-Modelle.',
        price: 'auf Anfrage',
        image: 'uploads/etb-akku-li-48v-2.jpg',
        specs: ['48V', '24Ah', 'Lithium', 'E-Scooter'],
        specsTable: [
          { label: 'Technologie', value: 'Lithium-Ionen' },
          { label: 'Spannung', value: '48V' },
          { label: 'Kapazität', value: '24Ah / 1152Wh' },
          { label: 'Entladestrom', value: 'max. 40A' },
          { label: 'Kompatibilität', value: 'TailG, Bikely E-Scooter' },
          { label: 'BMS-Schutz', value: 'Ja' },
        ],
        details: '<ul><li>Original Bikely Ersatzakku</li><li>BMS-Schutz gegen Überspannung und Tiefentladung</li><li>Passgenau für alle Bikely Modelle</li></ul>',
        delivery: 'Kostenloser Versand. Lieferzeit 3–5 Werktage.',
      },
    ],
  },
  usp: {
    eyebrow: 'Warum e-techbike.at?',
    title: 'Was uns unterscheidet',
    items: [
      { id: 'u1', title: 'Direktimport-Preise', description: 'Kein Zwischenhändler. Wir importieren direkt vom Hersteller und geben die volle Ersparnis weiter.' },
      { id: 'u2', title: '2 Jahre Garantie', description: 'Herstellergarantie auf alle Fahrzeuge und Akkus. Reparatur und Ersatzteile direkt bei uns.' },
      { id: 'u3', title: 'Persönliche Beratung', description: 'Testfahrten und Beratung vor Ort in Graz. Terminvereinbarung per Anruf oder E-Mail.' },
      { id: 'u4', title: 'Schnelle Lieferung', description: 'Österreichweiter Versand in 5–7 Werktagen. Vollversichert und mit Sendungsverfolgung.' },
      { id: 'u5', title: 'Förderungsberatung', description: 'Bis zu €1.800 staatliche Förderung. Wir begleiten Sie kostenlos durch die Beantragung.' },
      { id: 'u6', title: 'Werkstatt & Service', description: 'Vollständige Werkstatt in Graz. Wartung, Zubehör und Ersatzteile immer verfügbar.' },
    ],
  },
  news: {
    eyebrow: 'Neuigkeiten',
    title: 'Aktuell bei e-techbike.at',
    items: [
      {
        id: 'n1', date: '2026-05-01',
        title: 'Bis zu €1.800 E-Mobilitätsförderung — jetzt sichern!',
        body: 'Der Staat fördert E-Motorräder mit bis zu €1.800, E-Mopeds mit €1.200 und E-Klappräder mit €500. Gültig bis 31.03.2026 oder solange das Förderbudget reicht. Wir helfen bei der Antragstellung.',
      },
      {
        id: 'n2', date: '2026-04-15',
        title: 'Neue RKS E-Bike Modelle 2026 eingetroffen',
        body: 'Die neueste RKS-Kollektion ist da! Klappräder, City-Bikes und Fat Bikes — jetzt im Showroom in Graz vorbeikommen und Probefahrt vereinbaren.',
      },
      {
        id: 'n3', date: '2026-03-20',
        title: 'Werkstatt für alle E-Bike Marken geöffnet',
        body: 'Unsere Werkstatt in der Ghegagasse 29 ist für alle E-Bike und E-Scooter Marken geöffnet. Wartung, Ersatzteile und Zubehör direkt vor Ort.',
      },
    ],
  },
  contact: {
    title: 'Besuchen Sie uns in Graz.',
    subtitle: 'Persönliche Beratung, Testfahrten und direkte Abholung. Wir freuen uns auf Ihren Besuch.',
    email: 'graz@bikelyshop.at',
    phone: '+43 664 7372 6965',
    address: 'Ghegagasse 29, 8020 Graz, Österreich',
    whatsapp: '+436647372965',
    mapSrc: 'https://maps.google.com/maps?q=Ghegagasse+29,+8020+Graz,+Austria&output=embed&z=16',
    formEnabled: true,
  },
  whatsapp: {
    enabled: true,
    number: '+436647372965',
    message: 'Hallo! Ich interessiere mich für Ihre E-Bikes und möchte eine Beratung anfragen.',
  },
  footer: {
    brand: 'e-techbike.at',
    tagline: 'Direktimporteur für Premium-Elektromobilität',
    description: 'Österreichs Direktimporteur für Premium-Elektromobilität. Beratung, faire Preise, voller Service in Graz.',
    cols: [
      {
        title: 'Sortiment',
        links: [
          { label: 'E-Bikes', href: '#products' },
          { label: 'E-Mopeds', href: '#products' },
          { label: 'E-Scooter', href: '#products' },
          { label: 'Seniorenmobile', href: '#products' },
          { label: 'Batterien & Akkus', href: '#products' },
        ],
      },
      {
        title: 'Service',
        links: [
          { label: 'Über uns', href: '#location' },
          { label: 'Förderungen', href: '#foerderung' },
          { label: 'Werkstatt', href: '#location' },
          { label: 'Akku-Pflege', href: '#location' },
          { label: 'Kontakt', href: '#location' },
        ],
      },
      {
        title: 'Rechtliches',
        links: [
          { label: 'AGB', href: '/agb' },
          { label: 'Datenschutz', href: '/datenschutz' },
          { label: 'Impressum', href: '/impressum' },
        ],
      },
    ],
    links: [
      { label: 'AGB', href: '/agb' },
      { label: 'Datenschutz', href: '/datenschutz' },
      { label: 'Impressum', href: '/impressum' },
    ],
    copyright: '© 2026 e-techbike.at — made with love by RFI-IRFOS',
  },
}
